services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: api
    volumes:
      - ./:/app
    ports:
      - "8899:8899"
    env_file:
      - .env
    command: python src/app.py
    depends_on:
      - postgres

  dagster-webserver:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: dagster-webserver
    environment:
      DAGSTER_HOME: /app/dagster_home
    volumes:
      - ./dagster/dagster_home:/app/dagster_home
      - ./dagster/dagster_project:/app/dagster_project
      - ./src:/app/src
    ports:
      - "3000:3000"
    command: dagster-webserver -h 0.0.0.0 -p 3000
    depends_on:
      - dagster-daemon
      - postgres

  dagster-daemon:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: dagster-daemon
    environment:
      DAGSTER_HOME: /app/dagster_home
    volumes:
      - ./dagster/dagster_home:/app/dagster_home
      - ./dagster/dagster_project:/app/dagster_project
      - ./src:/app/src
    command: dagster-daemon run
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mmga
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
